OPENAI_API_KEY = "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"
STRIPE_SECRET_KEY = "sk_test_51QsKcZDCcCyM1zKD8oj3DTxX8yzGugX9hBmJjHuo6zwgZ4gELSStqkTdCrqNxOtmNQgwKRAfdveJc6WrY61eWpqr00jCXCq43C"
FIREBASE_CRED_PATH = "path/to/firebase-credentials.json"
